apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-rs
spec:
  replicas: 4
  selector: # Pod selector
    matchLabels:
      app: echo
      tier: app
  template: # matchLabels이 replicas만큼 없을 때 Pod생성
    metadata:
      labels:
        app: echo
        tier: app
    spec:
      containers:
        - name: echo
          image: ghcr.io/subicura/echo:v1
