apiVersion: v1
kind: Service
metadata:
  name: counter-lb
spec:
  type: LoadBalancer
  ports:
    - port: 30000 # 서비스가 생성할 포트
      targetPort: 3000 # 서비스가 접근할 Pod 포트 (default = port)
      protocol: TCP
  selector:
    app: counter
    tier: app
